name: Docker
on: [workflow_dispatch]

jobs:
    docker-jobs:
        runs-on: ubuntu-latest
        container:
            image: node:21-alpine3.18
            env:
              API_URL: some-url.com
            ports:
              - 80
        steps:
            - name: Log node & OS versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL

            